
name: PVPLib

description: none

authors: [坏黑]
website: http://www.15imc.com/index.html

main: me.skymc.pvplib.PVPLib

version: 1.2

commands: 
  pvplib:
    aliases: [pvp]
    permission: pvplib.use

soft-depend: [PlaceholderAPI]